[main]

# Time in seconds before the Job Status page closes itself after a successful job/print
# 0 means disabled
# job_complete_timeout: 0

# Time in seconds before the Job Status closes itself if an error is encountered
# job_error_timeout: 0

# If multiple printers are defined, this can be set the name of the one to show at startup.
# default_printer: MyPrinter

# To define a full set of custom menus (instead of merging user entries with default entries)
# set this to False. See Menu section below.
# use_default_menu: True

# Define one or more moonraker power devices that turn on/off with the screensaver (CSV list)
# screen_on_devices: example1, example2
# screen_off_devices:  example1, example2

# Define the password to use when locking the screen, this is not secure
# it's saved as plain text, it's meant to be a deterrent for kids or people at shows
# it will be redacted from the logs.
# default is no password
lock_password: lavanya17

# Auto-lock the screen after a period of inactivity (in seconds)
# 0 means disabled
autolock_timeout: 120

# Start KlipperScreen with the screen locked
start_locked: True

# Allow button focus to navigate with the keyboard
# a scroll wheel mapped to tab/shift+tab and enter button can work
# Beware that the UI is coded to be touchscreen controlled, this is
# not recommended as the only way to control
# keyboard_navigation: False
#~# --- Do not edit below this line. This section is auto generated --- #~#
#~#
#~# [main]
#~# theme = colorized
#~# screen_blanking = off
#~# screen_blanking_printing = off
#~# side_macro_shortcut = True
#~# font_size = small
#~# confirm_estop = True
#~# use_dpms = False
#~# show_heater_power = True
#~#
